name: Deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Copy files via SCP
      uses: appleboy/scp-action@master
      env:
        KEY: ${{ secrets.SSHKEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
      with:
        source: "*"
        target: "/home/ubuntu/app"

